version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  nifi:
    image: apache/nifi:1.27.0
    ports:
      - "9090:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.4.0
    depends_on:
      - kafka
      - minio
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: minioadmin
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: /etc/kafka-connect/plugins
    volumes:
      - ./plugins:/etc/kafka-connect/plugins

  minio:
    image: minio/minio
    ports:
      - "9000:9000"      # Console MinIO
      - "9001:9001"      # UI MinIO
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
  spark:
    build:
      context: .
      dockerfile: dockerfile.spark
    container_name: spark
    depends_on:
      - kafka
    ports:
      - "7077:7077"   # Spark master
      - "8081:8081"   # Spark web UI
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark-apps:/opt/spark/work-dir
      - ./spark-output:/opt/spark-output
    command: sleep infinity
volumes:
  minio-data:    
  nifi_conf: